default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: estimates
  username: drakefish

test:
  <<: *default
  database: estimates
  username: drakefish

production:
  <<: *default
  database: estimates
  username: deploy
